version: '3.8'
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    command: --innodb_buffer_pool_size=256M --innodb_log_file_size=256M
    volumes: [db_data:/var/lib/mysql]
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"  

  redis:
    image: redis:alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  wordpress:
    image: wordpress:6.8.1-php8.3-fpm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
      REDIS_HOST: redis
    volumes:
      - wp_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
      - ./wp-content/themes/saaslauncher:/var/www/html/wp-content/themes/saaslauncher
      - /etc/timezone:/etc/timezone:ro 
    depends_on: [db, redis]

  nginx:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - wp_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cache:/var/cache/nginx
volumes:
  db_data: {}
  wp_data: {}
  cache: {}
